import { resendClient } from "../utils/resend.js";
import { createWelcomeEmailTemplate } from "./emailTemplet.js";
const sender = {
  name: "Chatify",
  email: "onboarding@resend.dev"
};
export const sendWelcomeEmail=async(email,name,clientURL)=>{
    const {data,error}=await resendClient.emails.send({
        from: `${sender.name} <${sender.email}>`,
        to: email,
        subject: "Welcome to Chatify !",
        html: createWelcomeEmailTemplate(name,clientURL)
    })
    if(error){
        console.error("Error sending welcome email:", error);
        throw new Error("Failed to send welcome email");
    }
    console.log("Welcome email sent successfully:", data);
}
/*what is the use of this handler? => This handler is responsible for sending a welcome email to new users who 
sign up for the Chatify platform. It uses the Resend email service to send an email with a personalized welcome
 message and a link to the 
client application. The email content is generated using the createWelcomeEmailTemplate function,
 which creates an HTML template for the welcome email.
 and in more detail, the sendWelcomeEmail function takes three parameters: email, name, and clientURL.
- email: The email address of the recipient (the new user).
- name: The name of the recipient, which is used to personalize the email content.
- clientURL: The URL of the client application, which is included in the email as a call-to-action button.
The function uses the resendClient to send an email with the specified parameters. 
The email is sent from a predefined sender (configured in the .env file) and includes a subject line and HTML content 
generated by the createWelcomeEmailTemplate function. The template includes a personalized greeting, information about the 
platform, and a button that directs the user to the client application.

 */